spring:
  datasource:
    url: jdbc:postgresql://database:5432/tabllo-db
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.PostgreSQLDialect