services:
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "tabllo-db"
    volumes:
      - ./db/data:/var/lib/postgresql/data    # Save db data
      - ./db/init-scripts:/docker-entrypoint-initdb.d # Init tables
    ports:
      - "5432:5432"
  
  activemq:
    image: apache/activemq-classic:5.18.6
    environment:
      #ACTIVEMQ_CONF: "/opt/apache-activemq/conf"
      ACTIVEMQ_WRITE_LOGIN: "tabllo_user"
      ACTIVEMQ_WRITE_PASSWORD: "tabllo12345"
    #volumes:
      #- ./demo:/opt/apache-activemq/webapps-demo/demo    # demo web apps
      #- ./activeMQ/conf:/opt/apache-activemq/conf    # configuration
      #- ./activeMQ/data:/opt/apache-activemq/data    # data and logs
    ports:
      - "61613:61613" #stomp
      - "61614:61614" #ws
      - "61616:61616" #openwire
      - "8161:8161" #web admin GUI
    healthcheck:
      test: /opt/activemq/bin/activemq query --objname type=Broker,brokerName=*,service=Health | grep Good
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  client:
    build:
      context: ./
      target: client-dev
    develop:
      watch:
        - path: ./frontend-app/src
          action: sync
          target: usr/local/app/src
        - path: ./frontend-app/package.json
          action: rebuild
    ports: 
      - "3000:3000"